[package]
name = "zap_api"
version = "0.0.1"
authors = ["Simon Bennetts <psiinon@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
